# Generated by Django 2.1.1 on 2018-12-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('COOPW', 'Co-op Work Experience'), ('TECPR', 'Technical Project'), ('VOLUX', 'Volunteer Experience'), ('PROAF', 'Professional Affillation')], default='COOPW', max_length=5)),
                ('position', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('start_end_date', models.CharField(max_length=50, null=True, verbose_name='activity start and end dates')),
                ('attachments', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published')),
                ('detail', models.CharField(max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.ManyToManyField(to='resume.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.ManyToManyField(to='resume.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.SkillType'),
        ),
    ]
