# Generated by Django 2.1.1 on 2018-12-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20181225_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='detail',
            field=models.ManyToManyField(to='resume.Activity'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='detail',
            field=models.ManyToManyField(to='resume.Activity'),
        ),
    ]
