# Generated by Django 2.1.1 on 2018-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20181225_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetail',
            name='detail',
            field=models.CharField(max_length=300),
        ),
    ]
