# Generated by Django 2.1.1 on 2018-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityType',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
