# Generated by Django 2.1.1 on 2018-11-19 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_activity_activitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='detail',
            field=models.ManyToManyField(to='resume.Activity'),
        ),
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='detail',
            field=models.ManyToManyField(to='resume.Activity'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date publishesd'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='resume.SkillType'),
            preserve_default=False,
        ),
    ]
